language: objective-c
rvm: 2
osx_image: xcode7

before_script:
  - export LANG=en_US.UTF-8
  - bundle install
  - cd FBSnapshotTestCaseDemo
  - bundle exec pod install

script:
  - xcodebuild -workspace FBSnapshotTestCaseDemo.xcworkspace -scheme FBSnapshotTestCaseDemo -sdk iphonesimulator -destination 'name=iPhone 6' build test | xcpretty -c && exit ${PIPESTATUS[0]}
